INSERT INTO its_file (
    file_id,
    file_path,
    file_uuid,
    file_origin_name,
    file_size,
    create_date,
    last_update
) VALUES
(20001, '/asset/img/trading-room', 'trading-room-business-overview1', 'business-overview1.png', 0, NOW(), NOW()),
(20002, '/asset/img/trading-room', 'trading-room-solution1', 'solution1.png', 0, NOW(), NOW()),
(20003, '/asset/img/trading-room', 'trading-room-solution2', 'solution2.png', 0, NOW(), NOW()),
(20004, '/asset/img/trading-room', 'trading-room-solution3', 'solution3.png', 0, NOW(), NOW()),
(20005, '/asset/img/trading-room', 'trading-room-solution4', 'solution4.png', 0, NOW(), NOW()),
(20006, '/asset/img/trading-room', 'trading-room-solution5', 'solution5.png', 0, NOW(), NOW()),
(20007, '/asset/img/trading-room', 'trading-room-solution6', 'solution6.png', 0, NOW(), NOW()),
(20008, '/asset/img/trading-room', 'trading-room-solution7', 'solution7.png', 0, NOW(), NOW()),
(20009, '/asset/img/trading-room', 'trading-room-solution8', 'solution8.png', 0, NOW(), NOW()),
(20010, '/asset/img/trading-room', 'trading-room-solution9', 'solution9.png', 0, NOW(), NOW()),
(20011, '/asset/img/trading-room', 'trading-room-solution10', 'solution10.png', 0, NOW(), NOW()),
(20101, '/asset/img/trading-room', 'trading-room-success-case1', 'success-case1.png', 0, NOW(), NOW()),
(20102, '/asset/img/trading-room', 'trading-room-success-case2', 'success-case2.png', 0, NOW(), NOW()),
(20103, '/asset/img/trading-room', 'trading-room-success-case3', 'success-case3.png', 0, NOW(), NOW()),
(20104, '/asset/img/trading-room', 'trading-room-success-case4', 'success-case4.png', 0, NOW(), NOW()),
(20105, '/asset/img/trading-room', 'trading-room-success-case5', 'success-case5.png', 0, NOW(), NOW()),
(20106, '/asset/img/trading-room', 'trading-room-success-case6', 'success-case6.png', 0, NOW(), NOW()),
(20107, '/asset/img/trading-room', 'trading-room-success-case7', 'success-case7.png', 0, NOW(), NOW()),
(20108, '/asset/img/trading-room', 'trading-room-success-case8', 'success-case8.png', 0, NOW(), NOW()),
(20109, '/asset/img/trading-room', 'trading-room-success-case9', 'success-case9.png', 0, NOW(), NOW()),
(20110, '/asset/img/trading-room', 'trading-room-success-case10', 'success-case10.png', 0, NOW(), NOW()),
(20111, '/asset/img/trading-room', 'trading-room-success-case11', 'success-case11.png', 0, NOW(), NOW()),
(20112, '/asset/img/trading-room', 'trading-room-success-case12', 'success-case12.png', 0, NOW(), NOW()),
(20113, '/asset/img/trading-room', 'trading-room-success-case13', 'success-case13.png', 0, NOW(), NOW()),
(20114, '/asset/img/trading-room', 'trading-room-success-case14', 'success-case14.png', 0, NOW(), NOW()),
(20115, '/asset/img/trading-room', 'trading-room-success-case15', 'success-case15.png', 0, NOW(), NOW()),
(20116, '/asset/img/trading-room', 'trading-room-success-case16', 'success-case16.png', 0, NOW(), NOW()),
(20117, '/asset/img/trading-room', 'trading-room-success-case17', 'success-case17.png', 0, NOW(), NOW()),
(20118, '/asset/img/trading-room', 'trading-room-success-case18', 'success-case18.png', 0, NOW(), NOW()),
(20119, '/asset/img/trading-room', 'trading-room-success-case19', 'success-case19.png', 0, NOW(), NOW()),
(20120, '/asset/img/trading-room', 'trading-room-success-case20', 'success-case20.png', 0, NOW(), NOW()),
(20121, '/asset/img/trading-room', 'trading-room-success-case21', 'success-case21.png', 0, NOW(), NOW()),
(20122, '/asset/img/trading-room', 'trading-room-success-case22', 'success-case22.png', 0, NOW(), NOW()),
(20123, '/asset/img/trading-room', 'trading-room-success-case23', 'success-case23.png', 0, NOW(), NOW()),
(20124, '/asset/img/trading-room', 'trading-room-success-case24', 'success-case24.png', 0, NOW(), NOW());
